// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'dto.dart';
import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app`

void corgigramInit({required String dataDir}) =>
    RustLib.instance.api.crateApiCorgigramInit(dataDir: dataDir);

Future<SnapshotDto> getSnapshot() => RustLib.instance.api.crateApiGetSnapshot();

Future<ProfileDto> createIdentity({
  required String userId,
  required String displayName,
}) => RustLib.instance.api.crateApiCreateIdentity(
  userId: userId,
  displayName: displayName,
);

Future<String> getBundleQr() => RustLib.instance.api.crateApiGetBundleQr();

Future<ContactDto> addContact({required String bundleJson}) =>
    RustLib.instance.api.crateApiAddContact(bundleJson: bundleJson);

Future<List<MessageDto>> getMessages({required String contactId}) =>
    RustLib.instance.api.crateApiGetMessages(contactId: contactId);

Future<String> getSafetyNumber({required String contactId}) =>
    RustLib.instance.api.crateApiGetSafetyNumber(contactId: contactId);

Future<ConnectAutoDto> connectAuto({required String contactId}) =>
    RustLib.instance.api.crateApiConnectAuto(contactId: contactId);

Future<List<MessageDto>> syncMailbox({required String contactId}) =>
    RustLib.instance.api.crateApiSyncMailbox(contactId: contactId);

Future<MessageDto> sendMessage({
  required String contactId,
  required String text,
}) =>
    RustLib.instance.api.crateApiSendMessage(contactId: contactId, text: text);

Future<List<MessageDto>> pollIncoming() =>
    RustLib.instance.api.crateApiPollIncoming();

Future<void> saveConfig({
  String? firebaseDatabaseUrl,
  String? firebaseAuthToken,
}) => RustLib.instance.api.crateApiSaveConfig(
  firebaseDatabaseUrl: firebaseDatabaseUrl,
  firebaseAuthToken: firebaseAuthToken,
);

PushPayloadDto pushPayloadNewMessage({required String senderId}) =>
    RustLib.instance.api.crateApiPushPayloadNewMessage(senderId: senderId);

String defaultFirebaseUrl() =>
    RustLib.instance.api.crateApiDefaultFirebaseUrl();
