// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ConnectAutoDto {
  final String contactId;
  final bool connected;

  const ConnectAutoDto({required this.contactId, required this.connected});

  @override
  int get hashCode => contactId.hashCode ^ connected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectAutoDto &&
          runtimeType == other.runtimeType &&
          contactId == other.contactId &&
          connected == other.connected;
}

class ContactDto {
  final String userId;
  final String displayName;
  final String bundleJson;
  final String createdAt;

  const ContactDto({
    required this.userId,
    required this.displayName,
    required this.bundleJson,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      displayName.hashCode ^
      bundleJson.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          bundleJson == other.bundleJson &&
          createdAt == other.createdAt;
}

class MessageDto {
  final String id;
  final String contactId;
  final String direction;
  final String body;
  final String status;
  final String createdAt;

  const MessageDto({
    required this.id,
    required this.contactId,
    required this.direction,
    required this.body,
    required this.status,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      contactId.hashCode ^
      direction.hashCode ^
      body.hashCode ^
      status.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          contactId == other.contactId &&
          direction == other.direction &&
          body == other.body &&
          status == other.status &&
          createdAt == other.createdAt;
}

class ProfileDto {
  final String userId;
  final String displayName;
  final String bundleJson;
  final String safetyHint;

  const ProfileDto({
    required this.userId,
    required this.displayName,
    required this.bundleJson,
    required this.safetyHint,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      displayName.hashCode ^
      bundleJson.hashCode ^
      safetyHint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          bundleJson == other.bundleJson &&
          safetyHint == other.safetyHint;
}

class PushPayloadDto {
  final String kind;
  final String senderId;

  const PushPayloadDto({required this.kind, required this.senderId});

  @override
  int get hashCode => kind.hashCode ^ senderId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PushPayloadDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          senderId == other.senderId;
}

class SnapshotDto {
  final bool hasIdentity;
  final ProfileDto? profile;
  final List<ContactDto> contacts;
  final String? connectedContactId;
  final bool firebaseConfigured;
  final String firebaseDatabaseUrl;
  final String? firebaseDatabaseUrlOverride;
  final bool firebaseUsesDefaultUrl;
  final int outboxCount;

  const SnapshotDto({
    required this.hasIdentity,
    this.profile,
    required this.contacts,
    this.connectedContactId,
    required this.firebaseConfigured,
    required this.firebaseDatabaseUrl,
    this.firebaseDatabaseUrlOverride,
    required this.firebaseUsesDefaultUrl,
    required this.outboxCount,
  });

  @override
  int get hashCode =>
      hasIdentity.hashCode ^
      profile.hashCode ^
      contacts.hashCode ^
      connectedContactId.hashCode ^
      firebaseConfigured.hashCode ^
      firebaseDatabaseUrl.hashCode ^
      firebaseDatabaseUrlOverride.hashCode ^
      firebaseUsesDefaultUrl.hashCode ^
      outboxCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SnapshotDto &&
          runtimeType == other.runtimeType &&
          hasIdentity == other.hasIdentity &&
          profile == other.profile &&
          contacts == other.contacts &&
          connectedContactId == other.connectedContactId &&
          firebaseConfigured == other.firebaseConfigured &&
          firebaseDatabaseUrl == other.firebaseDatabaseUrl &&
          firebaseDatabaseUrlOverride == other.firebaseDatabaseUrlOverride &&
          firebaseUsesDefaultUrl == other.firebaseUsesDefaultUrl &&
          outboxCount == other.outboxCount;
}
