// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'dto.dart';
import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ProfileDto dco_decode_box_autoadd_profile_dto(dynamic raw);

  @protected
  ConnectAutoDto dco_decode_connect_auto_dto(dynamic raw);

  @protected
  ContactDto dco_decode_contact_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<ContactDto> dco_decode_list_contact_dto(dynamic raw);

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MessageDto dco_decode_message_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ProfileDto? dco_decode_opt_box_autoadd_profile_dto(dynamic raw);

  @protected
  ProfileDto dco_decode_profile_dto(dynamic raw);

  @protected
  PushPayloadDto dco_decode_push_payload_dto(dynamic raw);

  @protected
  SnapshotDto dco_decode_snapshot_dto(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ProfileDto sse_decode_box_autoadd_profile_dto(SseDeserializer deserializer);

  @protected
  ConnectAutoDto sse_decode_connect_auto_dto(SseDeserializer deserializer);

  @protected
  ContactDto sse_decode_contact_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<ContactDto> sse_decode_list_contact_dto(SseDeserializer deserializer);

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ProfileDto? sse_decode_opt_box_autoadd_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProfileDto sse_decode_profile_dto(SseDeserializer deserializer);

  @protected
  PushPayloadDto sse_decode_push_payload_dto(SseDeserializer deserializer);

  @protected
  SnapshotDto sse_decode_snapshot_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_profile_dto(
    ProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connect_auto_dto(
    ConnectAutoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contact_dto(ContactDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_contact_dto(
    List<ContactDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_profile_dto(
    ProfileDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_profile_dto(ProfileDto self, SseSerializer serializer);

  @protected
  void sse_encode_push_payload_dto(
    PushPayloadDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_snapshot_dto(SnapshotDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
