// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'dto.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 2138593181;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'corgigram_mobile',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ContactDto> crateApiAddContact({required String bundleJson});

  Future<ConnectAutoDto> crateApiConnectAuto({required String contactId});

  void crateApiCorgigramInit({required String dataDir});

  Future<ProfileDto> crateApiCreateIdentity({
    required String userId,
    required String displayName,
  });

  String crateApiDefaultFirebaseUrl();

  Future<String> crateApiGetBundleQr();

  Future<List<MessageDto>> crateApiGetMessages({required String contactId});

  Future<String> crateApiGetSafetyNumber({required String contactId});

  Future<SnapshotDto> crateApiGetSnapshot();

  Future<void> crateApiInitApp();

  Future<List<MessageDto>> crateApiPollIncoming();

  PushPayloadDto crateApiPushPayloadNewMessage({required String senderId});

  Future<void> crateApiSaveConfig({
    String? firebaseDatabaseUrl,
    String? firebaseAuthToken,
  });

  Future<MessageDto> crateApiSendMessage({
    required String contactId,
    required String text,
  });

  Future<List<MessageDto>> crateApiSyncMailbox({required String contactId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ContactDto> crateApiAddContact({required String bundleJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bundleJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_contact_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAddContactConstMeta,
        argValues: [bundleJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddContactConstMeta =>
      const TaskConstMeta(debugName: "add_contact", argNames: ["bundleJson"]);

  @override
  Future<ConnectAutoDto> crateApiConnectAuto({required String contactId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_connect_auto_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectAutoConstMeta,
        argValues: [contactId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectAutoConstMeta =>
      const TaskConstMeta(debugName: "connect_auto", argNames: ["contactId"]);

  @override
  void crateApiCorgigramInit({required String dataDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCorgigramInitConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorgigramInitConstMeta =>
      const TaskConstMeta(debugName: "corgigram_init", argNames: ["dataDir"]);

  @override
  Future<ProfileDto> crateApiCreateIdentity({
    required String userId,
    required String displayName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          sse_encode_String(displayName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateIdentityConstMeta,
        argValues: [userId, displayName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateIdentityConstMeta => const TaskConstMeta(
    debugName: "create_identity",
    argNames: ["userId", "displayName"],
  );

  @override
  String crateApiDefaultFirebaseUrl() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDefaultFirebaseUrlConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDefaultFirebaseUrlConstMeta =>
      const TaskConstMeta(debugName: "default_firebase_url", argNames: []);

  @override
  Future<String> crateApiGetBundleQr() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetBundleQrConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetBundleQrConstMeta =>
      const TaskConstMeta(debugName: "get_bundle_qr", argNames: []);

  @override
  Future<List<MessageDto>> crateApiGetMessages({required String contactId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetMessagesConstMeta,
        argValues: [contactId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetMessagesConstMeta =>
      const TaskConstMeta(debugName: "get_messages", argNames: ["contactId"]);

  @override
  Future<String> crateApiGetSafetyNumber({required String contactId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetSafetyNumberConstMeta,
        argValues: [contactId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSafetyNumberConstMeta => const TaskConstMeta(
    debugName: "get_safety_number",
    argNames: ["contactId"],
  );

  @override
  Future<SnapshotDto> crateApiGetSnapshot() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_snapshot_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetSnapshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSnapshotConstMeta =>
      const TaskConstMeta(debugName: "get_snapshot", argNames: []);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<MessageDto>> crateApiPollIncoming() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPollIncomingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPollIncomingConstMeta =>
      const TaskConstMeta(debugName: "poll_incoming", argNames: []);

  @override
  PushPayloadDto crateApiPushPayloadNewMessage({required String senderId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(senderId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_push_payload_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPushPayloadNewMessageConstMeta,
        argValues: [senderId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPushPayloadNewMessageConstMeta =>
      const TaskConstMeta(
        debugName: "push_payload_new_message",
        argNames: ["senderId"],
      );

  @override
  Future<void> crateApiSaveConfig({
    String? firebaseDatabaseUrl,
    String? firebaseAuthToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(firebaseDatabaseUrl, serializer);
          sse_encode_opt_String(firebaseAuthToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveConfigConstMeta,
        argValues: [firebaseDatabaseUrl, firebaseAuthToken],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveConfigConstMeta => const TaskConstMeta(
    debugName: "save_config",
    argNames: ["firebaseDatabaseUrl", "firebaseAuthToken"],
  );

  @override
  Future<MessageDto> crateApiSendMessage({
    required String contactId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendMessageConstMeta,
        argValues: [contactId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendMessageConstMeta => const TaskConstMeta(
    debugName: "send_message",
    argNames: ["contactId", "text"],
  );

  @override
  Future<List<MessageDto>> crateApiSyncMailbox({required String contactId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncMailboxConstMeta,
        argValues: [contactId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncMailboxConstMeta =>
      const TaskConstMeta(debugName: "sync_mailbox", argNames: ["contactId"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ProfileDto dco_decode_box_autoadd_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_profile_dto(raw);
  }

  @protected
  ConnectAutoDto dco_decode_connect_auto_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ConnectAutoDto(
      contactId: dco_decode_String(arr[0]),
      connected: dco_decode_bool(arr[1]),
    );
  }

  @protected
  ContactDto dco_decode_contact_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ContactDto(
      userId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      bundleJson: dco_decode_String(arr[2]),
      createdAt: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<ContactDto> dco_decode_list_contact_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_contact_dto).toList();
  }

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MessageDto dco_decode_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MessageDto(
      id: dco_decode_String(arr[0]),
      contactId: dco_decode_String(arr[1]),
      direction: dco_decode_String(arr[2]),
      body: dco_decode_String(arr[3]),
      status: dco_decode_String(arr[4]),
      createdAt: dco_decode_String(arr[5]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ProfileDto? dco_decode_opt_box_autoadd_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_profile_dto(raw);
  }

  @protected
  ProfileDto dco_decode_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ProfileDto(
      userId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      bundleJson: dco_decode_String(arr[2]),
      safetyHint: dco_decode_String(arr[3]),
    );
  }

  @protected
  PushPayloadDto dco_decode_push_payload_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PushPayloadDto(
      kind: dco_decode_String(arr[0]),
      senderId: dco_decode_String(arr[1]),
    );
  }

  @protected
  SnapshotDto dco_decode_snapshot_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SnapshotDto(
      hasIdentity: dco_decode_bool(arr[0]),
      profile: dco_decode_opt_box_autoadd_profile_dto(arr[1]),
      contacts: dco_decode_list_contact_dto(arr[2]),
      connectedContactId: dco_decode_opt_String(arr[3]),
      firebaseConfigured: dco_decode_bool(arr[4]),
      firebaseDatabaseUrl: dco_decode_String(arr[5]),
      firebaseDatabaseUrlOverride: dco_decode_opt_String(arr[6]),
      firebaseUsesDefaultUrl: dco_decode_bool(arr[7]),
      outboxCount: dco_decode_i_32(arr[8]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ProfileDto sse_decode_box_autoadd_profile_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_profile_dto(deserializer));
  }

  @protected
  ConnectAutoDto sse_decode_connect_auto_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_contactId = sse_decode_String(deserializer);
    var var_connected = sse_decode_bool(deserializer);
    return ConnectAutoDto(contactId: var_contactId, connected: var_connected);
  }

  @protected
  ContactDto sse_decode_contact_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_bundleJson = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return ContactDto(
      userId: var_userId,
      displayName: var_displayName,
      bundleJson: var_bundleJson,
      createdAt: var_createdAt,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<ContactDto> sse_decode_list_contact_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ContactDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_contact_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_contactId = sse_decode_String(deserializer);
    var var_direction = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return MessageDto(
      id: var_id,
      contactId: var_contactId,
      direction: var_direction,
      body: var_body,
      status: var_status,
      createdAt: var_createdAt,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProfileDto? sse_decode_opt_box_autoadd_profile_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_profile_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProfileDto sse_decode_profile_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_bundleJson = sse_decode_String(deserializer);
    var var_safetyHint = sse_decode_String(deserializer);
    return ProfileDto(
      userId: var_userId,
      displayName: var_displayName,
      bundleJson: var_bundleJson,
      safetyHint: var_safetyHint,
    );
  }

  @protected
  PushPayloadDto sse_decode_push_payload_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_senderId = sse_decode_String(deserializer);
    return PushPayloadDto(kind: var_kind, senderId: var_senderId);
  }

  @protected
  SnapshotDto sse_decode_snapshot_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hasIdentity = sse_decode_bool(deserializer);
    var var_profile = sse_decode_opt_box_autoadd_profile_dto(deserializer);
    var var_contacts = sse_decode_list_contact_dto(deserializer);
    var var_connectedContactId = sse_decode_opt_String(deserializer);
    var var_firebaseConfigured = sse_decode_bool(deserializer);
    var var_firebaseDatabaseUrl = sse_decode_String(deserializer);
    var var_firebaseDatabaseUrlOverride = sse_decode_opt_String(deserializer);
    var var_firebaseUsesDefaultUrl = sse_decode_bool(deserializer);
    var var_outboxCount = sse_decode_i_32(deserializer);
    return SnapshotDto(
      hasIdentity: var_hasIdentity,
      profile: var_profile,
      contacts: var_contacts,
      connectedContactId: var_connectedContactId,
      firebaseConfigured: var_firebaseConfigured,
      firebaseDatabaseUrl: var_firebaseDatabaseUrl,
      firebaseDatabaseUrlOverride: var_firebaseDatabaseUrlOverride,
      firebaseUsesDefaultUrl: var_firebaseUsesDefaultUrl,
      outboxCount: var_outboxCount,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_profile_dto(
    ProfileDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_profile_dto(self, serializer);
  }

  @protected
  void sse_encode_connect_auto_dto(
    ConnectAutoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.contactId, serializer);
    sse_encode_bool(self.connected, serializer);
  }

  @protected
  void sse_encode_contact_dto(ContactDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.bundleJson, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_contact_dto(
    List<ContactDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_contact_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.contactId, serializer);
    sse_encode_String(self.direction, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_profile_dto(
    ProfileDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_profile_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_profile_dto(ProfileDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.bundleJson, serializer);
    sse_encode_String(self.safetyHint, serializer);
  }

  @protected
  void sse_encode_push_payload_dto(
    PushPayloadDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.senderId, serializer);
  }

  @protected
  void sse_encode_snapshot_dto(SnapshotDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.hasIdentity, serializer);
    sse_encode_opt_box_autoadd_profile_dto(self.profile, serializer);
    sse_encode_list_contact_dto(self.contacts, serializer);
    sse_encode_opt_String(self.connectedContactId, serializer);
    sse_encode_bool(self.firebaseConfigured, serializer);
    sse_encode_String(self.firebaseDatabaseUrl, serializer);
    sse_encode_opt_String(self.firebaseDatabaseUrlOverride, serializer);
    sse_encode_bool(self.firebaseUsesDefaultUrl, serializer);
    sse_encode_i_32(self.outboxCount, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
